##  Iris classification

In [19]:
from mosaicml import *
from mosaicml.constants import MLModelFlavours
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
from sklearn import svm

In [20]:
iris = datasets.load_iris()
digits = datasets.load_digits()
X = iris.data
y = iris.target

# IRIS First Model Creation

In [21]:
clf = RandomForestClassifier(random_state=0, n_jobs=-1)

In [22]:
xtrain, xtest, ytrain, ytest = train_test_split(X,y,test_size=0.2, random_state=0)
clf = clf.fit(xtrain, ytrain)

In [23]:
y_pred=clf.predict(xtest)
print(xtest.shape)
print(ytest.shape)
print(xtrain.shape)
print(ytrain.shape)

(30, 4)
(30,)
(120, 4)
(120,)


In [24]:
prob=clf.predict_proba(xtest)
#print(prob)
prob1=prob[:,1]

# Iris Second Model Creation

In [25]:
clf_2 = RandomForestClassifier(random_state=123, n_jobs=10)
xtrain2, xtest2, ytrain2, ytest2 = train_test_split(X,y,test_size=0.25, random_state=123)
clf_2 = clf_2.fit(xtrain2, ytrain2)
y_pred2=clf_2.predict(xtest2)
print(xtest2.shape)
print(ytest2.shape)
print(xtrain2.shape)
print(ytrain2.shape)
prob_2=clf_2.predict_proba(xtest2)[:,1]

(38, 4)
(38,)
(112, 4)
(112,)


### score 1st Model

In [26]:
@scoring_func
def score_1(model, request):
    import numpy
    payload = request.json["payload"]
    data_list = payload
    data_array = numpy.asarray(data_list)
    prediction = model.predict(data_array)
    return prediction.tolist()

### score 2nd Model

In [27]:
@scoring_func
def score_2(model, request):
    import numpy
    payload = request.json["payload"]
    data_list = payload
    data_array = numpy.asarray(data_list)
    prediction = model.predict(data_array)
    return prediction.tolist()

In [28]:
import requests
req = requests.Request()
req.json = {"payload":[[5.8, 2.8, 5.1, 2.4],
       [6.0 , 2.2, 4.0 , 1.0 ]]}

In [29]:
xtest[:2]

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ]])

In [30]:
we=score_1(clf,req)

In [31]:
import numpy as np
per = np.array(we)


In [32]:
per*0.5

array([1. , 0.5])

In [33]:
xtest2[0]

array([6.3, 2.5, 4.9, 1.5])

In [34]:
import requests
req2 = requests.Request()
req2.json = {"payload":[[6.3, 2.5, 4.9, 1.5]]}

In [35]:
score_2(clf_2,req2)

[1]

# Registering 1st model

In [36]:
register_model(clf,
                score_1,
                "sklearn_iris_v11_a",
                "sklearn_iris_v11_a",
                MLModelFlavours.sklearn,
                input_type="json",
                explain_ai=True,
                x_train=xtrain, 
                y_train=ytrain,
                y_true=ytest,
                y_pred=y_pred,
                model_type="classification",
                prob=prob1,
                feature_names=iris.feature_names,
                feature_ids=iris.feature_names,
                target_names=iris.target_names.tolist()
              )

Calculating build time metrics

Progress: ██████████████████████████████████████████████████████████████████████ 100.0%


2020-10-21 11:01:00,234 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:01:00,331 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[25/25] grid cells ████████████████████ Time elapsed: 6 seconds

2020-10-21 11:01:09,131 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:01:09,136 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[22/22] grid cells ████████████████████ Time elapsed: 5 seconds

2020-10-21 11:01:16,932 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:01:16,937 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[25/25] grid cells ████████████████████ Time elapsed: 6 seconds

2020-10-21 11:01:25,831 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:01:25,834 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[22/22] grid cells ████████████████████ Time elapsed: 6 seconds

2020-10-21 11:01:34,247 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progress_bar=False
2020-10-21 11:01:34,332 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[4/4] features ████████████████████ Time elapsed: 1 seconds

2020-10-21 11:01:36,789 - skater.core.global_interpretation.tree_surrogate - INFO - post pruning applied ...
2020-10-21 11:01:36,795 - skater.core.global_interpretation.tree_surrogate - INFO - Scorer used cross-entropy
2020-10-21 11:01:36,798 - skater.core.global_interpretation.tree_surrogate - INFO - original score using base model 2.1094237467877998e-15
2020-10-21 11:01:36,932 - skater.core.global_interpretation.tree_surrogate - INFO - Summary: childrens of the following nodes are removed []
2020-10-21 11:01:36,934 - skater.core.global_interpretation.tree_surrogate - INFO - Done generating prediction using the surrogate, shape (120, 3)
2020-10-21 11:01:36,937 - skater.core.global_interpretation.tree_surrogate - INFO - Done scoring, surrogate score 0.0; oracle score 0.034
2020-10-21 11:01:36,938 - skater.core.global_interpretation.tree_surrogate - WARNING - impurity score: 0.034 of the surrogate model is higher than the impurity threshold: 0.01. The higher the impurity score, lower is

{'created_by': 'amit.boke@lntinfotech.com',
 'created_on': '2020-10-21T11:00:53+00:00',
 'deploymentstatus': False,
 'description': 'sklearn_iris_v11_a',
 'flavour': 'sklearn',
 'id': 'e27cce6c-119f-433a-9e1a-2b6efc2f4b85',
 'last_modified_by': 'amit.boke@lntinfotech.com',
 'last_modified_on': '2020-10-21T11:00:53+00:00',
 'name': 'sklearn_iris_v11_a',
 'project_id': 'b9c02804-b1ca-4103-a3e6-43d454a6ef8a',
 'type': 'model',
 'versions': [{'created_by': 'amit.boke@lntinfotech.com',
   'created_on': '2020-10-21T11:00:53+00:00',
   'datasource_name': '',
   'deploy_info': None,
   'deployments': [],
   'description': None,
   'docker_image_url': 'registry.lti-aiq.in:443/mosaic-ai-logistics/mosaic-ai-serving:1.0.0-30092020',
   'id': '557d00dd-681c-46a4-bab8-1fdfb5decc6d',
   'init_script': '"pip install --user absl-py==0.10.0\\n pip install --user alembic==1.4.3\\n pip install --user astor==0.8.1\\n pip install --user astroid==2.3.3\\n pip install --user async-generator==1.10\\n pip insta

# Registering 2nd model

In [37]:
register_model(clf_2,
                score_2,
                "sklearn_iris_v22_a",
                "sklearn_iris_v22_a",
                MLModelFlavours.sklearn,
                input_type="json",
                explain_ai=True,
                x_train=xtrain2, 
                y_train=ytrain2,
                y_true=ytest2,
                y_pred=y_pred2,
                model_type="classification",
                prob=prob_2,
                feature_names=iris.feature_names,
                feature_ids=iris.feature_names,
                target_names=iris.target_names.tolist()
              )

Calculating build time metrics

Progress: ██████████████████████████████████████████████████████████████████████ 100.0%


2020-10-21 11:02:16,134 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:02:16,230 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[25/25] grid cells ████████████████████ Time elapsed: 6 seconds

2020-10-21 11:02:27,331 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:02:27,336 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[22/22] grid cells ████████████████████ Time elapsed: 6 seconds

2020-10-21 11:02:35,831 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:02:35,836 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[24/24] grid cells ████████████████████ Time elapsed: 6 seconds

2020-10-21 11:02:44,031 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-10-21 11:02:44,035 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[21/21] grid cells ████████████████████ Time elapsed: 5 seconds

2020-10-21 11:02:52,033 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progress_bar=False
2020-10-21 11:02:52,036 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[4/4] features ████████████████████ Time elapsed: 1 seconds

2020-10-21 11:02:54,667 - skater.core.global_interpretation.tree_surrogate - INFO - post pruning applied ...
2020-10-21 11:02:54,672 - skater.core.global_interpretation.tree_surrogate - INFO - Scorer used cross-entropy
2020-10-21 11:02:54,675 - skater.core.global_interpretation.tree_surrogate - INFO - original score using base model 2.1094237467878e-15
2020-10-21 11:02:54,735 - skater.core.global_interpretation.tree_surrogate - INFO - Summary: childrens of the following nodes are removed []
2020-10-21 11:02:54,829 - skater.core.global_interpretation.tree_surrogate - INFO - Done generating prediction using the surrogate, shape (112, 3)
2020-10-21 11:02:54,833 - skater.core.global_interpretation.tree_surrogate - INFO - Done scoring, surrogate score 0.0; oracle score 0.027
2020-10-21 11:02:54,834 - skater.core.global_interpretation.tree_surrogate - WARNING - impurity score: 0.027 of the surrogate model is higher than the impurity threshold: 0.01. The higher the impurity score, lower is th

{'created_by': 'amit.boke@lntinfotech.com',
 'created_on': '2020-10-21T11:02:10+00:00',
 'deploymentstatus': False,
 'description': 'sklearn_iris_v22_a',
 'flavour': 'sklearn',
 'id': 'bba07e9a-97d3-4b2e-8af9-8d8305fc6f2a',
 'last_modified_by': 'amit.boke@lntinfotech.com',
 'last_modified_on': '2020-10-21T11:02:10+00:00',
 'name': 'sklearn_iris_v22_a',
 'project_id': 'b9c02804-b1ca-4103-a3e6-43d454a6ef8a',
 'type': 'model',
 'versions': [{'created_by': 'amit.boke@lntinfotech.com',
   'created_on': '2020-10-21T11:02:10+00:00',
   'datasource_name': '',
   'deploy_info': None,
   'deployments': [],
   'description': None,
   'docker_image_url': 'registry.lti-aiq.in:443/mosaic-ai-logistics/mosaic-ai-serving:1.0.0-30092020',
   'id': '00b5d327-c17e-4b0b-8cbb-d3289fec8d97',
   'init_script': '"pip install --user absl-py==0.10.0\\n pip install --user alembic==1.4.3\\n pip install --user astor==0.8.1\\n pip install --user astroid==2.3.3\\n pip install --user async-generator==1.10\\n pip insta

# Ensemble model registration

In [ ]:
from mosaicml import *
from mosaicml.constants import MLModelFlavours

In [22]:
import requests
req_ensemble = requests.Request()
req_ensemble1 = requests.Request()
req_ensemble2 = requests.Request()
req_ensemble1.json = {"payload":[[5.8, 2.8, 5.1, 2.4]]}
req_ensemble2.json = {"payload":[[5.8, 2.8, 5.1, 2.4]]}
req_ensemble.json = {"model1":{"payload":[[5.8, 2.8, 5.1, 2.4],
       [6.0 , 2.2, 4.0 , 1.0 ]]},"model2":{"payload":[[5.8, 2.8, 5.1, 2.4],
       [6.0 , 2.2, 4.0 , 1.0 ]]}}

### Ensemble model Score function

In [23]:
import json
@scoring_func
def score_ensemble(model_dict, request):
    model1=model_dict["0a452277-9602-414f-8c20-844ad3f6d5db"]["model_object"]
    score1=model_dict["0a452277-9602-414f-8c20-844ad3f6d5db"]["score_object"]
    model2=model_dict["a262a8b9-a295-4cec-8961-84d9b7393cac"]["model_object"]
    score2=model_dict["a262a8b9-a295-4cec-8961-84d9b7393cac"]["score_object"]
    request1=request.json["model1"]
    request2=request.json["model2"]
    import numpy as np
    import requests
    req_ensemble1 = requests.Request()
    req_ensemble2 = requests.Request()
    req_ensemble1.json=request1
    req_ensemble2.json=request2
    a=score1(model1,req_ensemble1)
    b=score2(model2,req_ensemble2)
    model1_prob = np.array(a)
    model2_prob = np.array(b)
    final_prob = model1_prob*0.5 + model2_prob*0.5
    return final_prob.tolist()

# Registering Ensemble Model

In [24]:
help(register_ensemble_model)

Help on function register_ensemble_model in module mosaicml.api:

register_ensemble_model(name, description, version_list, scoring_func, init_script=None)
    Register ensemble model to the mosaic ai server
    
    Args:
        name (string): name of the model
        description (string): description of the model
        version_list (list): list of versions of dependent models required for final prediction
        E.g [ "v1", "v2"]
        scoring_func (function): function to be used for scoring
        init_script(string):script provided by user
    Returns:
        dict



In [25]:
version_list = ["0a452277-9602-414f-8c20-844ad3f6d5db","a262a8b9-a295-4cec-8961-84d9b7393cac"]

In [26]:
register_ensemble_model(name="first_ensemble_model_iris_33",description="testing",version_list=version_list,scoring_func=score_ensemble)

{'created_by': 'kunal',
 'created_on': '2020-10-15T06:22:28+00:00',
 'deploymentstatus': False,
 'description': 'testing',
 'flavour': 'ensemble',
 'id': '1b24a132-1a55-4603-834e-83f986b33d7f',
 'last_modified_by': 'kunal',
 'last_modified_on': '2020-10-15T06:22:28+00:00',
 'name': 'first_ensemble_model_iris_33',
 'project_id': 'b9c02804-b1ca-4103-a3e6-43d454a6ef8a',
 'type': 'model',
 'versions': [{'created_by': 'kunal',
   'created_on': '2020-10-15T06:22:28+00:00',
   'datasource_name': '',
   'deploy_info': None,
   'deployments': [],
   'description': None,
   'docker_image_url': 'registry.lti-aiq.in:443/mosaic-ai-logistics/mosaic-ai-serving:1.0.0-30092020',
   'id': '8ec9ad09-29e5-489d-b608-2b81b1e84b2b',
   'init_script': '"pip install --user absl-py==0.9.0 alembic==1.4.2 astor==0.8.1 async-generator==1.10 attrs==19.3.0 backcall==0.1.0 beautifulsoup4==4.9.1 bleach==3.1.3 blis==0.4.1 bs4==0.0.1 cachetools==4.1.1 category-encoders==2.2.2 certifi==2020.6.20 chardet==3.0.4 click==7.1